### PR TITLE
Update showcase

### PR DESCRIPTION
**Pull request by daileytj**
Fixes PXBLUE-1524.

#### Changes proposed in this Pull Request:
- Update navigation
- Update the showcase with:
  - All of the material ui components
  - All of the pxblue react components

### CODE REVIEW

**Comment by daileytj** [comment]
Putting up a draft PR just to get eyes on this along the way. Not nearly finished and there's already a handful of ``` @TODO:``` comments in here that I need to get to, but feel free to comment along the way.

**Comment by joebochill** [comment]
Looking good so far. A couple initial thoughts...

- We'll probably want to break down the PX Blue components similarly to how you're doing the Material ones (what we have on that page now is more like what I would consider to be a page template). We'll be able to show the components in a variety of different configurations (sort of like a combination page of the different storybook stories)
- Might need to break down some of the material components even further...lots of the input elements are going to have a ton of states (combinations of outlined, dense, primary, secondary, disabled) and might quickly blow out the cards you have allocated for them.

**Comment by joebochill** [comment]
Is this ready for review @daileytj ?

**Comment by daileytj** [comment]
> Is this ready for review @daileytj ?

Not quite.

**Review by joebochill — APPROVED** [review]

**Pull request merged**
