### PR TITLE
Bug/change the material UI imports to default

### PR DESCRIPTION
**Pull request by bkarambe**
Fixes https://github.com/pxblue/react-component-library/issues/321

#### Changes proposed in this Pull Request:
- Changed import statements of material-ui components to default imports
- Comp props and other things than components still be imported as named imports

#### Screenshots:
**Bundle analysis on showcase**
Screenshot 2021-09-30 at 8 25 50 PM

**Bundle analysis on new blank cli project**
ss_original

#### To Test:
1. Start a new React project with the pxblue cli via command line prompt npx -p @pxblue/cli pxb new (https://pxblue.github.io/development/cli) 
2. Run yarn build from the root of the react-component-library in the updated branch you have locally.
3. The previous command should create a dist folder... copy the contents of that dist folder into your new cli generated projects node_modules/@pxblue/react-native-components folder.
4. Add the source-map-explorer to the cli generated project as a dev dependency and add "analyze" script "analyze": "source-map-explorer 'build/static/js/*.js'" 
5. Run yarn build in the new cli project
6. Run yarn analyze
7. Compare the new chart to the one posted in the PR

### CODE REVIEW

**Comment by emclaug2** [comment]
Could you provide a before vs after pic of the bundle analysis?  I'm not sure what it looks like before.

**Comment by bkarambe** [comment]
> Could you provide a before vs after pic of the bundle analysis? I'm not sure what it looks like before.

@emclaug2  Added screenshots in the description (1st comment).

**Review by joebochill — APPROVED** [review]
So...you didn't actually have to change the import syntax here in the showcase project since we aren't concerned with the bundle size. 

For some context around this, there is one team (Green Team) who has very serious limitations on the size of the application that can fit on their hardware (something like 500kb max), so they need to squeeze every possible kB they can get. They are only using a couple of the Material UI components, so they don't want the code for any of the other components to show up in their bundle (wasted space). So we made sure that our component library doesn't accidentally include all of the Material-UI components by updating the syntax there. Here in the showcase, we are showing off almost all of the Material components, so there are very few that we aren't using (not much bundle size savings) and we aren't deploying this anywhere, so the ultimate bundle sign isn't of much consequence to us.

That being said, it doesn't hurt anything to do it this way. And actually using this syntax for the icons actually might save us a fair bit of bundle size since we aren't showing off all of the icons and the complete icon set is actually pretty large.

**Comment by joebochill** [comment]
Make sure you run yarn and commit your updated yarn.lock file

**Pull request merged**
