### PR TITLE
Update to use the latest beta themes

### PR DESCRIPTION
**Pull request by joebochill**
#### Changes proposed in this Pull Request:
- Use the latest beta theme package with the color updates

### CODE REVIEW

**Comment by joebochill** [comment]
> does beta.1 have everything for all colors, light and dark? Drawer dose not match up with our react storybook on dark theme

The latest beta.1 theme has all of the color updates for light and dark. If you are cloning this repository directly, some of the components may look weird because in order to use version 6 of the themes you need to use the latest version of the component library as well (I don't know if we have that published in a beta or not yet). 

I'm working with this as a submodule of the component library, which has the latest. We'll need a subsequent update here for that package once we publish it.

**Comment by jeffvg** [comment]
> > does beta.1 have everything for all colors, light and dark? Drawer dose not match up with our react storybook on dark theme
> 
> The latest beta.1 theme has all of the color updates for light and dark. If you are cloning this repository directly, some of OUR components may look weird because in order to use version 6 of the themes you need to use the latest version of the component library as well (I don't know if we have that published in a beta or not yet).
> 
> I'm working with this as a submodule of the component library, which has the latest. We'll need a subsequent update here for that package once we publish it.

ok yep. I updated react-components locally to v5.0.0 and the drawer looks good now. (not up to snuff here been a while)

**Comment by joebochill** [comment]
> > > does beta.1 have everything for all colors, light and dark? Drawer dose not match up with our react storybook on dark theme
> > 
> > 
> > The latest beta.1 theme has all of the color updates for light and dark. If you are cloning this repository directly, some of OUR components may look weird because in order to use version 6 of the themes you need to use the latest version of the component library as well (I don't know if we have that published in a beta or not yet).
> > I'm working with this as a submodule of the component library, which has the latest. We'll need a subsequent update here for that package once we publish it.
> 
> ok yep. I updated react-components locally to v5.0.0 and the drawer looks good now. (not up to snuff here been a while)

Word. I bumped the version of the component library up too since there is a beta available after all.

Don't feel bad — this is the first case where you actually kinda need to update both packages at the same time on the React side of things, so you're not far from snuff.

**Comment by jeffvg** [comment]
I'm running latest with packages below. Everything looks ok except for primary color in dark theme. There is a mix of blue[500] and blue[200].
"@material-ui/core": "^4.11.3",
"@material-ui/icons": "^4.11.2",
"@material-ui/styles": "^4.11.3",
"@pxblue/colors": "^3.0.0",
"@pxblue/icons-mui": "^2.2.2",
"@pxblue/react-components": "5.0.0-beta.0"

List item tag is using blue[200]
Empty state using blue[200] for font and blue[500] on button
things like that....

**Comment by joebochill** [comment]
You need to be using 5.0.1 of the component library to get the latest color updates (current latest available verison on npm is 5.0.0). I'll publish a new beta with the current updates to avoid the confusion.

Good catch on the ListItemTag colors...that's something I missed...I'll make a new PR that fixes that.

**Comment by jeffvg** [comment]
ok everything looks better now with latest components beta. I did notice the drawer footer could use a little tweaking on dark theme.

image
image

* DSM

image

**Comment by joebochill** [comment]
> ok everything looks better now with latest components beta. I did notice the drawer footer could use a little tweaking on dark theme.

Let's log a new issue for that...the purpose of this PR is just to update the package versions...I did not have intentions of making updates to the showcase contents here.

**Review by jeffvg — APPROVED** [review]

**Pull request merged**
